install.packages("quantmod")
install.packages("PortfolioAnalytics")
install.packages("PerformanceAnalytics")
install.packages("ROI")
install.packages("ROI.plugin.glpk")
install.packages("ROI.plugin.quadprog")
library(quantmod)
library(PortfolioAnalytics)
library(PerformanceAnalytics)
library(ROI)
library(ROI.plugin.glpk)
library(ROI.plugin.quadprog)
symbols <- c("AAPL", "MSFT", "GOOGL", "AMZN")
getSymbols(symbols, from = "2020-01-01", to = "2024-01-01")
prices <- merge(Ad(AAPL), Ad(MSFT), Ad(GOOGL), Ad(AMZN))
portfolio_returns <- diff(log(prices))
portfolio_returns <- na.omit(portfolio_returns)
colnames(portfolio_returns) <- c("AAPL", "MSFT", "GOOGL", "AMZN")
port_spec <- portfolio.spec(assets = colnames(portfolio_returns))
port_spec <- add.constraint(portfolio = port_spec, type = "full_investment")
port_spec <- add.constraint(portfolio = port_spec, type = "long_only")
port_spec <- add.objective(portfolio = port_spec, type = "risk", name = "var")
port_spec <- add.objective(portfolio = port_spec, type = "return", name = "mean")
opt_portfolio <- optimize.portfolio(R = portfolio_returns, 
                                    portfolio = port_spec, 
                                    optimize_method = "ROI")
print(opt_portfolio)
chart.Weights(opt_portfolio, main = "Optimized Portfolio Weights")
extract_returns <- extractStats(opt_portfolio)
plot(opt_portfolio, chart.type = "risk_return", main = "Portfolio Optimization: Risk vs Return")